---
title: "AccuracyDist_1"
author: "Olga Alieva"
date: "2022-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load packages
```{r message=FALSE}
library(tidyverse)
library(yardstick)
```

# Load data
```{r}
load("/Users/olga/R_Workflow/compareDist/data/CanbNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/CanbS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/ClarNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/ClarS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/CosNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/CosS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/EuclNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/EuclS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/JeffNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/Labbe.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/ManhNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/ManhS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/TanNS.Rdata")
load("/Users/olga/R_Workflow/compareDist/data/TanS.Rdata")
```

# Bind data
```{r}
data_w <- manh_s %>% 
  bind_rows(manh_ns) %>% 
  bind_rows(eucl_ns) %>% 
  bind_rows(eucl_s) %>% 
  bind_rows(cos_ns) %>% 
  bind_rows(cos_s) %>% 
  bind_rows(tan_ns) %>% 
  bind_rows(tan_s) %>% 
  bind_rows(canb_ns) %>% 
  bind_rows(canb_s) %>% 
  bind_rows(clar_ns) %>% 
  bind_rows(clar_s) %>% 
  bind_rows(jeff_ns) %>% 
  bind_rows(labbe) 
```

# Get mean accuracy for each method
```{r}
acc_all <- data_w %>% 
  group_by(method, scale, mfw, size, id) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  group_by(method, scale) %>% 
  summarise(mean = mean(.estimate)) %>% 
  mutate(mean = round(mean, 3)) %>% 
  arrange(-mean)
write_csv(acc_all, "AccAll.csv")
```

# Delete methods with very low performace
```{r}
data_w <- manh_s %>% 
  bind_rows(manh_ns) %>% 
  bind_rows(eucl_ns) %>% 
  bind_rows(cos_ns) %>% 
  bind_rows(cos_s) %>% 
  bind_rows(tan_ns) %>% 
  bind_rows(canb_ns) %>% 
  bind_rows(clar_ns) %>% 
  bind_rows(jeff_ns) %>% 
  bind_rows(labbe)
```


# Accuracy by mfw / sample size
```{r}
png(filename="AccW.png",width=1000, height=436)
data_w %>% 
  mutate(mfw = cut(mfw, breaks=c(0, 200, 400, 600, 800, 1000), 
                   labels=paste0("mfw", c(200, 400, 600, 800, 1000),
                                 sep=""))) %>% 
  group_by(size, mfw, method, scale) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  ggplot(aes(x = size, y=.estimate, color = mfw)) +
  geom_line() + 
  theme(legend.position = c(0.8, 0.2)) +
  facet_wrap(facets = ~method + scale, nrow = 2) +
  theme_bw() + 
  xlab("длина отрывка") +
  ylab("точность")
dev.off()
```

# Maximum accuracy 
```{r}
top_w <- data_w %>% 
  group_by(method, scale, mfw, size, id) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  group_by(method, scale, mfw, size) %>% 
  summarise(mean = mean(.estimate)) %>% 
  mutate(mean = round(mean, 3)) %>% 
  ungroup() %>% 
  top_n(wt = mean, n=20) %>% 
  arrange(-mean)
write_csv(top_w, "TopW.csv")
```

# Max accuracy for short text
```{r}
short <- data_w %>% 
  filter(size %in% c(1000, 1500, 2000)) %>% 
  group_by(method, scale, mfw, size) %>%
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) 

top_short <- short %>%
  top_n(wt = .estimate, n=100) %>% 
  arrange(-.estimate)

top_short_sel <- top_short %>%
  group_by(size) %>% 
  top_n(2, wt=.estimate) %>% 
  mutate(.estimate = round(.estimate, 3))
write_csv(top_short_sel, "TopShort.csv")
```

# Standard deviation
```{r}
cos_s_1500_400 <- data_w %>% 
  filter(size == 1500, method == "cosine",
         scale == TRUE, mfw == 400) %>% 
  group_by(id) %>%
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  pull(.estimate)

sd(cos_s_1500_400)
mean(cos_s_1500_400)

cos_s_2000_700 <- data_w %>% 
  filter(size == 2000, method == "cosine",
         scale == TRUE, mfw == 700) %>% 
  group_by(id) %>%
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  pull(.estimate)

sd(cos_s_2000_700)
mean(cos_s_2000_700)

tan_1000_800 <- data_w %>% 
  filter(size == 1000, method == "tanimoto",
         scale == FALSE, mfw == 800) %>% 
  group_by(id) %>%
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  pull(.estimate)

sd(tan_1000_800)
mean(tan_1000_800)

```


# Where classifiers fail
```{r}
data_w %>% filter(method == "cosine", scale == T) %>% 
  group_by(expected) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  arrange(.estimate)

data_w %>% filter(method == "labbe") %>% 
  group_by(expected) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  arrange(.estimate)

data_w %>% filter(method == "tanimoto", scale == F) %>% 
  group_by(expected) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  arrange(.estimate)
```

# Common errors
```{r}
errors <- data_w %>% filter(method == "cosine", scale == T,
                  expected %in% c("Aristotle", "Aristides", 
                                  "Demosthenes")) %>%
  group_by(expected) %>% 
  count(predicted) %>% ungroup() %>% 
  group_by(expected) %>% 
  slice_max(n, n = 4)
  
write_csv(errors, "Errors3W.csv")
```

# Where classifiers perform best
```{r}
data_w %>% filter(method == "cosine", scale == T) %>% 
  group_by(expected) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  arrange(-.estimate)

data_w %>% filter(method == "labbe") %>% 
  group_by(expected) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  arrange(-.estimate)

data_w %>% filter(method == "tanimoto", scale == F) %>% 
  group_by(expected) %>% 
  accuracy(truth = expected, estimate = predicted) %>% 
  select(-.metric, -.estimator) %>% 
  arrange(-.estimate)
```



