---
title: "PrepareCorpus"
author: "Olga Alieva"
date: "2022-12-10"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description 

This file contains code for extracting a corpus of Ancient Greek texts from Perseus.

## Load libraries
```{r}
library(dplyr)
library(rperseus)
library(stringr)
library(tidytext)
library(ggplot2)
```

## RPerseus: Select Authors and Works
```{r}
# group names
group_names <- c("Lucianus", "Gorgias", "Antisthenes", "Lysias", "Isocrates", "Alcidamas", "Polybius", "Herodotus", "Plotinus", "Plutarch")

# subset authors
subset_authors <- perseus_catalog %>% 
  filter(group_name %in% group_names,
         language == "grc")

# select < 5 texts for each author
names <- subset_authors %>% 
  group_by(group_name) %>% 
  count() %>% 
  filter(n > 4) %>% 
  pull(group_name) 

Isocrates <- subset_authors %>% 
  filter(group_name == "Isocrates", 
         label %in% c("Busiris", "To Nicocles", "Against the Sophists")) 

Lysias <- subset_authors %>% filter(group_name == "Lysias", 
                                    label %in% c("Olympic Oration", "Funeral Oration", "Against Eratosthenes"))

Plutarch <- subset_authors %>% filter(group_name == "Plutarch",
                                      label %in% c("Solon", "Alcibiades", "Romulus"))
  
subset_join <- subset_authors %>% 
  filter(!group_name %in% names) %>% 
  bind_rows(Plutarch, Lysias, Isocrates) %>% 
  select(-description, -language)

subset_join %>% 
  group_by(group_name) %>% 
  count() 

subset_join %>% 
  count(n()) 
```

## Retrieve texts
```{r message=FALSE, warning=FALSE}
# pull urns
urns <- subset_join %>% 
  pull(urn)

# get texts
corpus <- tibble()
for (i in 1:length(urns)) {
  message(paste("getting text", i, "out of", length(urns)))
  text <- get_perseus_text(urn = urns[i])
  corpus <- text %>% bind_rows(corpus)
}

# tidy up
corpus <- corpus %>% 
  select(-urn, -language, -description, -section) %>% 
  rename(author = group_name, work = label) %>% 
  relocate(text, .after = last_col())
```

# Tokenize texts and preprocess
```{r}
# remove several capital Greek letters in a row 
corpus$text <- corpus$text %>% 
  str_remove_all("[:upper:]{2,}")

# remove Latin characters (mostly editorial notes)
corpus$text <- corpus$text %>% 
  str_remove_all("[A-Za-z]")

# remove punctuation
corpus$text <- corpus$text %>% 
  str_remove_all("[:punct:]")

# tokenize (this will be a very long data!)
corpus <- corpus %>% 
  unnest_tokens(word, text)

nrow(corpus)
```

# Inspect corpus
```{r}
# compare text lengths
corpus %>% group_by(author) %>% 
  count() %>%
  ggplot(aes(x = reorder(author, n), y = n, fill=author)) +
  geom_col(show.legend = F) + 
  coord_flip() + 
  theme_bw() + 
  xlab(NULL)
```

# Sample authors with single texts
```{r}
# select Plotinus and Herodotus
Pl_Her <- corpus %>% 
  filter(author %in% c("Plotinus", "Herodotus")) %>% 
  group_by(author, work) %>% 
  mutate(sample = round((row_number() + 15000) / 15000)) %>% 
  filter(sample < 4)
```

# Join samples and whole texts
```{r}
corpus_all <- corpus %>% 
  filter(!author %in% c("Plotinus", "Herodotus")) %>% 
  bind_rows(Pl_Her) # NAs will be produced
```

# Plot corpus size
```{r}
# plot
corpus_all %>% 
  group_by(author) %>% 
  count() %>%
  ggplot(aes(x = reorder(author, n), y = n, fill=author)) +
  geom_col(show.legend = F) + 
  coord_flip() + 
  theme_bw() + 
  xlab(NULL)
```

# Corpus Stats
```{r}
corpus_all %>% group_by(author) %>% count()
```

# Plot Sample Size
```{r}
# plot sample size
corpus_all %>% group_by(work, sample) %>% count() %>%
  ggplot(aes(x=n)) + geom_freqpoly()
```

# Add Group IDs
```{r}
# add group ids
groups <- corpus_all %>% group_by(author, work, sample) %>% 
  mutate(group_id = cur_group_id())
ids <- sort(unique(groups$group_id))
ids
```

# Write text Files
```{r message=FALSE}
# write text files 
for(i in ids){
  message(paste("processing sample ", i))
  author <- groups %>% filter(group_id == i) %>% 
    pull(author) %>% unique()
  title <- groups %>% filter(group_id == i) %>% 
    pull(work) %>% unique()
  id <- i
  text <- groups %>% filter(group_id == i) %>% pull(word)
  filename <- paste0(author, "_", title, "_", id, ".txt")
  write.table(text, file = filename, row.names = FALSE, 
              col.names = FALSE, quote = FALSE)
}
```
